[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip=lib/ccip/',
    '@chainlink/local/=lib/chainlink-local/',
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/hJpT7kumpfp1uTEyiHTJG8R5qyOaI1Pe"
arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/hJpT7kumpfp1uTEyiHTJG8R5qyOaI1Pe"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
